name: Deploy on Push

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: shivamrock887466/myapp:latest

      - name: Verify pushed image
        run: docker pull shivamrock887466/myapp:latest





      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/private.key
          chmod 600 ~/.ssh/private.key
          
      - name: Connect and Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/private.key ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} '
           sudo docker pull shivamrock887466/myapp:latest &&
           sudo docker stop myapp || true &&
           sudo docker rm myapp || true &&
           sudo docker run -d --name myapp -p 3000:3000 shivamrock887466/myapp:latest
          '


      
