name: Deploy on Push

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: shivamrock887466/myapp:latest

      - name: Verify pushed image
        run: docker pull shivamrock887466/myapp:latest

      - name: Decode SSH Key
        run: |
          echo "$SSH_KEY" | base64 -d > id_rsa
          chmod 600 id_rsa
        env:
          SSH_KEY: ${{ secrets.EC2_SSH_KEY }}


      - name: Read private key content into ENV
        id: load_key
        run: |
            echo "::set-output name=private_key::$(cat id_rsa)"
  
      - name: SSH using decoded id_rsa content
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ steps.load_key.outputs.private_key }}
          port: 22
          script: |
           sudo docker pull shivamrock887466/myapp:latest
           sudo docker stop myapp || true
           sudo docker rm myapp || true
           sudo docker run -d --name myapp -p 3000:3000 shivamrock887466/myapp:latest
           
          
      
