name : on push
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: log in to docker registry
        uses: docker/login-action@v1
        with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: shivamrock887466/myapp:latest

      - name: varify pushed image
        run: docker pull shivamrock887466/myapp:latest


      - name: Deploy to Ec2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}

          scripts: |
           sudo docker pull shivamrock887466/myapp:latest
           sudo docker stop myapp || true
           sudo docker rm myapp || true
           sudo docker run -d --name myapp -p 3000:3000 shivamrock887466/myapp:latest